### ISSUE TITLE
Tabel doet het niet

### ISSUE THREAD

**Issue by RRochelleH** [Werkgroep-Toetsen-Op-Afstand/keuzetool-toetsen#9]
https://github.com/Werkgroep-Toetsen-Op-Afstand/keuzetool-toetsen/blob/116b3fd710aded388e3cf4f48dd8c2fa1d2c1941/content/methods/oral_exam/approach.md?plain=1#L31

**Comment by ShKlinkenberg** [comment]
opgelost
